# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-04 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, verbose_name='标识')),
                ('tag', models.CharField(max_length=32, verbose_name='版本')),
                ('status', models.IntegerField(choices=[(1, '待发布'), (2, '发布中'), (3, '成功'), (4, '失败')], default=1, verbose_name='发布状态')),
                ('before_download_script', models.TextField(blank=True, null=True, verbose_name='下载前脚本')),
                ('after_download_script', models.TextField(blank=True, null=True, verbose_name='下载后脚本')),
                ('before_deploy_script', models.TextField(blank=True, null=True, verbose_name='发布前脚本')),
                ('after_deploy_script', models.TextField(blank=True, null=True, verbose_name='发布后脚本')),
            ],
        ),
        migrations.CreateModel(
            name='HookTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('hook_type', models.IntegerField(choices=[(2, '下载前'), (4, '下载后'), (6, '发布前'), (8, '发布后')], verbose_name='钩子类型')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='项目名')),
                ('repo', models.CharField(max_length=128, verbose_name='仓库地址')),
                ('env', models.CharField(choices=[('prod', '正式'), ('test', '测试')], default='test', max_length=16, verbose_name='环境')),
                ('path', models.CharField(max_length=128, verbose_name='线上项目地址')),
            ],
            options={
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('ip', models.CharField(max_length=32, verbose_name='ip')),
            ],
            options={
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='servers',
            field=models.ManyToManyField(to='v1.Server', verbose_name='关联服务器'),
        ),
        migrations.AddField(
            model_name='deploytask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Project', verbose_name='项目'),
        ),
    ]
