# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('ip', models.CharField(max_length=32, verbose_name='ip')),
            ],
            options={
                'verbose_name_plural': '服务器',
            },
        ),
    ]
