# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, verbose_name='节点文字')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Node', verbose_name='父节点')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Server', verbose_name='父节点')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.DeployTask', verbose_name='发布任务')),
            ],
        ),
    ]
