# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-20 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '项目'},
        ),
    ]
